### ISSUE TITLE
Pruebas Unitarias

### ISSUE THREAD

**Issue by Luz1727** [SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-recyclanexus#1]
[Practica7-PruebasUnitarias.pdf](https://github.com/SistemasTecTlaxiaco/actividad-11-practica-de-pruebas-unitarias-recyclanexus/files/15491213/Practica7-PruebasUnitarias.pdf)

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
